#!/usr/bin/env bash

#customize a 404 page redirection

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/KisingiMichael permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites_enabled/defaulti
#creating 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_error="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_error/" /etc/nginx/sites-enabled/default

#restart nginx server after successful redirections
sudo srvice nginx restart
